[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Required by openzeppelin-foundry-upgrades to run upgrade-safety validations.
ffi = true
ast = true
build_info = true
optimizer = true
optimizer_runs = 999
via_ir = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/swap-router-contracts/=lib/swap-router-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
