[book]
title = "PropAMM SDK"
description = "SDKs for interacting with the PropAMM contracts"
authors = ["LambdaClass"]
language = "en"
src = "src"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/lambdaclass/propamm-router-contracts"
